version: '3.4'

services:
  miniecommerceapp.webapi:
    image: registry.digitalocean.com/aspnetwithredis/miniecommerceappwebapi
    build:
      context: .
      dockerfile: MiniECommerceApp.WebApi/Dockerfile
  redis:
    image: redis:latest
    volumes:
      - ./redis_data:/data
    ports:
      - "6379:6379"  
  rabbitmq:
    image: rabbitmq:3-management
    hostname: my-rabbitmq-server
    ports:
      - "5672:5672"
      - "15672:15672"
  prometheus:
    image: ubuntu/prometheus
    container_name: prometheus
    ports:
      - "5100:9090"
    environment:
      - TZ=UTC
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "5200:3000"
    volumes:
      - ./grafana-data/data:/var/lib/grafana